python -W ignore main.py \
    --root_path=/home/kimyh/python/project/transformer \
    --dataset_name=ECU_EngineSpeed \
    --purpose=predict \
    --device_num=1 \
    --epochs=1000 \
    --batch_size=8 \
    --train_p=0.9 \
    --max_grad_norm=100 \
    --loss_function_name=CrossEntropyLoss \
    --optimizer_name=SGD \
    --learning_rate=0.5 \
    --scheduler_name=StepLR \
    --gamma=0.98 \
    --max_length=601 \
    --num_embeddings=3000 \
    --head_num=8 \
    --d_model=512 \
    --layer_num=6 \
    --dropout_p=0.2 \
    --shuffle= \
    --drop_last= \
    --num_workers=5 \
    --pin_memory=True
    